<a href="https://colab.research.google.com/github/hyturing/Machine-Learning/blob/main/practice_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
t = np.array([1, 2, 3, 4, 5])
print(t)

[1 2 3 4 5]


In [6]:
s = 1/(1+np.exp(-t))
ds = s*(1-s)

In [7]:
print(ds)

[0.19661193 0.10499359 0.04517666 0.01766271 0.00664806]


In [9]:
ds.shape

(5,)

In [13]:
ds = ds.reshape(5, 1)

In [14]:
ds.shape

(5, 1)

In [15]:
k = ds.shape

In [16]:
print(k)

(5, 1)


In [17]:
print(ds.shape[0])

5


In [23]:
import math

def norm(x):
  sum = 0
  for i in range(x.shape[0]):
    sum += x[i]*x[i]
  sum = math.sqrt(sum)

  x = x/sum
  return x

In [24]:
print(norm(ds))

[[0.86156268]
 [0.4600868 ]
 [0.19796623]
 [0.0773988 ]
 [0.0291321 ]]


In [22]:
x_norm = np.linalg.norm(ds, axis = 1, keepdims = True)
print(x_norm)

[[0.19661193]
 [0.10499359]
 [0.04517666]
 [0.01766271]
 [0.00664806]]


In [27]:
np.linalg.norm(ds, axis = 1, keepdims = True)

array([[0.19661193],
       [0.10499359],
       [0.04517666],
       [0.01766271],
       [0.00664806]])